### PR TITLE
Create awsome books again using modules

### PR DESCRIPTION
**Pull request by mohamedgamaleldin999999**
in this PR, I am trying to create the awsome books app using modules. I am also trying to add an updated clock.

### CODE REVIEW

**Review by TadesseDev — CHANGES_REQUESTED** [review]
### Hi @mohamedgamaleldin999999 

### I'm Tadesse Alemayehu your reviewer for this PR. :hand: 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request 🛑🛑
yPkfDFf

- [ ] Dear @mohamedgamaleldin999999, I have read about what happened in your request for a review description, But unfortunately, we are not able to review a project unless all the changes are visible in the pull request. In the case you mention I suggest you do... 
1. Merge all your changes to the future branch.
2. hard reset your main branch to the earliest commit point. 
3. push both branches (main and feature) 
4. open a pull request from the feature branch to the main branch. (since your changes are in the feature branch and your main branch is reset, this should work fine)

### Good luck 👋

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by shahadat3669 — CHANGES_REQUESTED** [review]
Hi @mohamedgamaleldin999999 , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.



## Invalid Code Review Request

You have submitted a project, that does not pass all the linter requirements.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by mohamedgamaleldin999999** [comment]
@shahadat3669 
Thanks for your response. 

Can you please help me on how to fix that? I already stated in the message to you that all the linter errors are in the installed Luxon files and I shouldn't be changing them. For the node module, I have added it to gitignore file and I do not know why ut is still failing. Please help. Thanks in advance.

**Review by brytebee — CHANGES_REQUESTED** [review]
Hi, @mohamedgamaleldin999999 👋,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

# Status: Invalid Code Review Request




You have submitted a project, that has failed linter checks.
Since this project hasn't been reviewed, you could transfer the code to a new repo. Ensure you ignore the node modules from the local git before pushing.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @brytebee in your question so I can receive the notification.
### _**Use @brytebee on slack for faster responses.**_

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Pull request merged**
